[OSC-241] Bug fixes on FTP on Linux migration
UiPath/Script.Activities pull request #181
Opened 2021-09-27 09:14 UTC by petcua1

2021-09-28 12:46 UTC, ovidiuiliescu requested changes

2021-09-28 12:46 UTC, ovidiuiliescu commented on Activities/Shared/UiPath.Shared.Activities/ContinuableAsyncNativeActivity.cs
> +                if (continueOnError)
A better solution would be to define `ContinueOnError` as abstract in this class.

Then all derived classes would be forced to implement it properly.

See how this is done in the main Activities repository.

2021-10-08 12:17 UTC, petcua1 commented on Activities/Shared/UiPath.Shared.Activities/ContinuableAsyncNativeActivity.cs
> +                if (continueOnError)
fixed

2021-10-08 12:19 UTC, ovidiuiliescu approved these changes

2021-10-11 07:50 UTC, ovidiuiliescu approved these changes

2021-10-11 07:51 UTC, merged