OSAC-247 StudioWeb activities for Database package
UiPath/Script.Activities pull request #189
Opened 2021-11-02 13:31 UTC by mateisimionescu

Description
StudioWeb activities for Database package
How to test
Open Activity package in Studio Web
Jira
[OSAC-247](https://uipath.atlassian.net/browse/OSAC-247)
Label:
24S

2021-11-03 06:57 UTC, alcxs requested changes
please fix individual comments

2021-11-03 06:57 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/UiPath.Database.Activities.csproj
> +
remove this whitespace

2021-11-03 06:57 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/Resources/ActivitiesMetadata.json
> +      "IconKey": null,
@ovidiuiliescu - do we need icons for this activity package?

2021-11-03 06:57 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Design/DesignerMetadata.cs
> -            builder.AddCustomAttributes(typeof(BulkUpdate), new DisplayNameAttribute(Resources.BulkUpdate));
Validate that this resources (old activity names) are no longer used and remove them from RESX (no longer required - cluttering the RESX)

2021-11-05 08:19 UTC, petcua1 approved these changes

2021-11-05 09:03 UTC, petcua1 commented
Squash the 2 commits to have only one commit

2021-11-05 09:03 UTC, petcua1 requested changes
Squash Commits to have only one

2021-11-08 14:14 UTC, alcxs requested changes
looks good, small formatting issues, see individual comments

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/BulkInsertViewModel.cs
> +
remove white space

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/BulkInsertViewModel.cs
> +
remove white space

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/BulkUpdateViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/BulkUpdateViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/DatabaseConnectViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/DatabaseConnectViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/ExecuteNonQueryViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/ExecuteNonQueryViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/ExecuteQueryViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities/NetCore/ViewModels/ExecuteQueryViewModel.cs
> +
remove extra line

2021-11-08 14:14 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Design/Properties/SharedResources.cs
> +    public class SharedResources : UiPath_Database_Activities
add an XML summary tag description (public class)

2021-11-09 13:46 UTC, alcxs requested changes
see individual comments. please rebase first, before fixing

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +		<PackageId>Matei.Database.Activities</PackageId>
Remove this change in package name. It will break compatibility with older versions of the package.

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +		<TargetFrameworks>net461;net5.0-windows;net5.0</TargetFrameworks>
please stop auto-indentation as it appears as modified, even if it's not

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +		<PackageTitle>UiPath.Database.Activities</PackageTitle>
please stop auto-indentation as it appears as modified, even if it's not

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +			<BuildOutputInPackage Include="$(OutputPath)UiPath.Database.pdb" />
please stop auto-indentation as it appears as modified, even if it's not

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +			<BuildOutputInPackage Include="$(OutputPath)es\UiPath.Database.resources.dll" TargetPath="es\UiPath.Database.resources.dll" />
please stop auto-indentation as it appears as modified, even if it's not

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +			<BuildOutputInPackage Include="$(OutputPath)es-MX\UiPath.Database.Activities.resources.dll" TargetPath="es-MX\UiPath.Database.Activities.resources.dll" />
please stop auto-indentation as it appears as modified, even if it's not

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +			<BuildOutputInPackage Include="$(OutputPath)UiPath.Data.ConnectionUI.Dialog.dll" />
please stop auto-indentation as it appears as modified, even if it's not

2021-11-09 13:46 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Packaging/UiPath.Database.Activities.Packaging.csproj
> +			<BuildOutputInPackage Include="$(OutputPath)runtimes\win-x86\native\sni.dll" TargetPath="runtimes\win-x86\native\sni.dll" />
please stop auto-indentation as it appears as modified, even if it's not

2021-11-11 08:24 UTC, alcxs approved these changes

2021-11-16 14:47 UTC, ovidiuiliescu approved these changes

2021-11-16 14:49 UTC, ovidiuiliescu approved these changes

2021-11-17 07:56 UTC, petcua1 approved these changes

2021-11-17 08:37 UTC, merged