OSAC-252 StudioWeb activities for FTP package
UiPath/Script.Activities pull request #194
Opened 2021-11-15 12:30 UTC by mateisimionescu

Description
StudioWeb activities for FTP package
How to test
Open Activity package in Studio Web
Jira
OSAC-252
Label:
24S

2021-11-15 12:35 UTC, alcxs approved these changes

2021-11-16 15:40 UTC, ovidiuiliescu approved these changes

2021-11-17 09:42 UTC, petcua1 requested changes

2021-11-17 09:42 UTC, petcua1 commented on Activities/FTP/UiPath.FTP.Activities/UiPath.FTP.Activities.csproj
> +  <ItemGroup>
Why do we have Remove and then Add?

2021-11-17 12:01 UTC, petcua1 approved these changes

2021-11-17 12:51 UTC, merged