[OSAC-257] StudioWeb activities for Cryptography package
UiPath/Script.Activities pull request #195
Opened 2021-11-22 10:53 UTC by mateisimionescu

Description
StudioWeb activities for Cryptography package
How to test
Open Activity package in Studio Web
Jira
[OSAC-257](https://uipath.atlassian.net/browse/OSAC-257)
Label:
24S

2021-11-22 12:22 UTC, alcxs requested changes
see comments and apply same to all view models

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities.Packaging/UiPath.Cryptography.Activities.Packaging.csproj
> +      <BuildOutputInPackage Include="$(OutputPath)UiPath.Cryptography.pdb" />
alignment fix

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptFileViewModel.cs
> +            InputFilePath.Widget = new DefaultWidget { Type = ViewModelWidgetType.Input };
remove Inputs to leave SW to decide what better editor to use. Similar for all InArgument<string> properties

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptFileViewModel.cs
> +            OutputFilePath.Widget = new DefaultWidget { Type = ViewModelWidgetType.Input };
remove Inputs to leave SW to decide what better editor to use. Similar for all InArgument properties

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptFileViewModel.cs
> +        {
remove if you do not have additional code for this method

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptFileViewModel.cs
> +        protected override async ValueTask InitializeModelAsync()
remove if you do not have additional code for this method

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptTextViewModel.cs
> +            Input.Widget = new DefaultWidget { Type = ViewModelWidgetType.Input };
remove Input. see previous messages

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptTextViewModel.cs
> +            Key.Widget = new DefaultWidget { Type = ViewModelWidgetType.Input };
remove Input. see previous messages

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptTextViewModel.cs
> +            Encoding.Widget = new DefaultWidget { Type = ViewModelWidgetType.Input };
remove Input. see previous messages

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptTextViewModel.cs
> +        protected override async ValueTask InitializeModelAsync()
remove override method if no additional code

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/DecryptTextViewModel.cs
> +        protected override void InitializeRules()
remove override method if no additional code

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/EncryptFileViewModel.cs
> +            InputFilePath.Widget = new DefaultWidget { Type = ViewModelWidgetType.Input };
remove Input, see previous comments

2021-11-22 12:22 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/ViewModels/EncryptFileViewModel.cs
> +        protected override async ValueTask InitializeModelAsync()
see previous comments

2021-11-23 13:40 UTC, alcxs requested changes
please review comments and fix

2021-11-23 13:40 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities.Packaging/UiPath.Cryptography.Activities.Packaging.csproj
> +      <BuildOutputInPackage Include="$(OutputPath)UiPath.Cryptography.pdb" />
still an issue

2021-11-23 13:40 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities.Packaging/UiPath.Cryptography.Activities.Packaging.csproj
> +	<VersionSuffix></VersionSuffix>
align issues, as well

2021-11-23 13:40 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/Properties/UiPath.Cryptography.Activities.resx
> +  <data name="EncodingDisplayName" xml:space="preserve">
why are this still here, please remove all unused resources

2021-11-23 13:40 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/Properties/UiPath.Cryptography.Activities.resx
> -	<data name="EncryptTextEncodingDescription" xml:space="preserve">
why are this still here, please remove all unused resources

2021-12-06 10:31 UTC, alcxs approved these changes

2021-12-08 09:33 UTC, ovidiuiliescu approved these changes

2021-12-08 09:33 UTC, merged