OSAC-260 - Update Resource for Database activities to match FIGMA des…
UiPath/Script.Activities pull request #199
Opened 2021-12-10 11:05 UTC by mateisimionescu

…igns

2021-12-10 11:50 UTC, alcxs requested changes
small formatting issues, otherwise looks good

2021-12-10 11:50 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Design/UiPath.Database.Activities.Design.csproj
> +	<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="3.21.1" PrivateAssets="All" />
why the spacing? please remove

2021-12-10 11:50 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Design/UiPath.Database.Activities.Design.csproj
> +	<PackageReference Include="UiPath.Activities.Contracts" />
remove extra spacing

2021-12-10 11:50 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Design/DesignerMetadata.cs
> +
remove this

2021-12-16 13:21 UTC, alcxs approved these changes
minor styling issues

2021-12-16 13:21 UTC, alcxs commented on Activities/Database/UiPath.Database.Activities.Design/UiPath.Database.Activities.Design.csproj
> +	<PackageReference Include="UiPath.Activities.Contracts" />
spacing please

2021-12-16 13:21 UTC, alcxs commented on Activities/Directory.build.targets
> +	<PackageReference Update="UiPath.Activities.Api" Version="21.12.0-alpha.6604" PrivateAssets="All" />
spacing

2021-12-17 13:20 UTC, ovidiuiliescu approved these changes

2021-12-17 13:20 UTC, merged