[OSAC-284] Update dependent packages (platform, Studio, Api) to match other packages (21.12-preview)
UiPath/Script.Activities pull request #205
Opened 2021-12-15 16:13 UTC by mateisimionescu

Description
Update dependent packages
How to test
Open Activity package in Studio Web
Jira
OSAC-284
Label:
24S

2021-12-16 09:03 UTC, alcxs requested changes
please check versions for ALL packages and update accordingly

2021-12-16 09:03 UTC, alcxs commented on Activities/Directory.build.targets
>      <PackageReference Update="UiPath.Robot.Api" Version="21.6.0-beta.4360" PrivateAssets="All" />
please check versions for packages that are 21.6.*

2021-12-16 09:03 UTC, alcxs commented on Activities/Directory.build.targets
>      <PackageReference Update="UiPath.Activities.Contracts" Version="21.6.0-beta.4360" PrivateAssets="All" />
same here

2021-12-16 14:41 UTC, alcxs approved these changes

2021-12-17 13:19 UTC, ovidiuiliescu requested changes

2021-12-17 13:19 UTC, ovidiuiliescu commented on Activities/Directory.build.targets
> +    <PackageReference Update="System.Activities.ViewModels" Version="1.0.0-20211215.1"/>
At least for ViewModels there's a newer version out, please use that.

2022-01-10 10:57 UTC, ovidiuiliescu approved these changes

2022-01-10 10:57 UTC, merged