OSAC-275 - Add deprecated to the algos
UiPath/Script.Activities pull request #206
Opened 2021-12-16 11:10 UTC by radunegulescu2

Description
StudioWeb activities for Cryptography package
How to test
Open Activity package in Studio
Jira
OSAC-275
Label:
24S

2021-12-16 13:19 UTC, alcxs requested changes
Comments only

2021-12-16 13:19 UTC, alcxs commented on Activities/Cryptography/UiPath.Cryptography.Activities/NetCore/DataSourceHelper.cs
> +    internal static class DataSourceHelper
XML comments please

2021-12-16 13:19 UTC, alcxs commented on Activities/Shared/UiPath.Shared/LocalizedEnum.cs
> +        public static LocalizedEnum GetLocalizedValue(Type enumType, object value)
XML Comments

2021-12-17 09:09 UTC, alcxs approved these changes

2021-12-17 13:18 UTC, ovidiuiliescu approved these changes

2021-12-17 13:18 UTC, merged