OSAC-261-Update Resource for FTP activities to match FIGMA designs
UiPath/Script.Activities pull request #224
Opened 2022-01-21 07:56 UTC by viseanadrianiulian

Description
Update Resource for FTP activities to match FIGMA designs
How to test
Open Activity package in Studio Web and Studio Desktop
Jira
OSAC-261
Label:
24S

2022-01-21 08:52 UTC, alcxs requested changes
minor styling changes and comments

2022-01-21 08:52 UTC, alcxs commented on Activities/FTP/UiPath.FTP.Activities.Design/ActivitySynonymApiRegistration.cs
> +    internal class ActivitySynonymApiRegistration : ApiRegistrationBase
XML Comment on all public / internal members

2022-01-21 08:52 UTC, alcxs commented on Activities/FTP/UiPath.FTP.Activities.Design/DesignerMetadata.cs
> +        public void Initialize(object api)
XML Comment

2022-01-21 08:52 UTC, alcxs commented on Activities/FTP/UiPath.FTP.Activities.Design/DesignerMetadata.cs
>          public void Register()
add a space before this line

2022-01-21 08:52 UTC, alcxs commented on Activities/FTP/UiPath.FTP.Activities.Design/ApiRegistrationBase.cs
> +    internal abstract class ApiRegistrationBase
XML Comment on all public / internal members

2022-01-25 14:38 UTC, viseanadrianiulian commented on Activities/FTP/UiPath.FTP.Activities.Design/ActivitySynonymApiRegistration.cs
> +    internal class ActivitySynonymApiRegistration : ApiRegistrationBase
done

2022-01-25 14:38 UTC, viseanadrianiulian commented on Activities/FTP/UiPath.FTP.Activities.Design/DesignerMetadata.cs
>          public void Register()
done

2022-01-25 14:38 UTC, viseanadrianiulian commented on Activities/FTP/UiPath.FTP.Activities.Design/ApiRegistrationBase.cs
> +    internal abstract class ApiRegistrationBase
done

2022-01-25 14:38 UTC, viseanadrianiulian commented on Activities/FTP/UiPath.FTP.Activities.Design/DesignerMetadata.cs
> +        public void Initialize(object api)
done

2022-01-31 14:30 UTC, alcxs approved these changes

2022-02-10 09:21 UTC, ovidiuiliescu requested changes

2022-02-10 09:21 UTC, ovidiuiliescu commented on Activities/FTP/UiPath.FTP.Activities.Design/ActivitySynonymApiRegistration.cs
> +        protected override void PerformRegistration(IWorkflowDesignApi api)
Please add `[MethodImpl(MethodImplOptions.NoInlining)]` to this method.

See how other activity packs do this (e.g. Mail in the main Activities repo).

2022-04-11 10:11 UTC, ovidiuiliescu approved these changes

2022-04-11 10:11 UTC, merged