[OSAC-374] - WIP - Invoke Powershell - crossplatform
UiPath/Script.Activities pull request #274
Opened 2022-07-20 08:37 UTC by nicolae-anghel

https://uipath.atlassian.net/browse/OSAC-374

2022-07-20 08:56 UTC, alcxs requested changes
see individual comments

2022-07-20 08:56 UTC, alcxs commented on Activities/.nuget/NuGet.targets
> +        <NuGetToolsPath>$([System.IO.Path]::Combine($(SolutionDir), ".nuget"))</NuGetToolsPath>
this needs to be validated against the other APs

2022-07-20 08:56 UTC, alcxs commented on Activities/.nuget/NuGet.targets
> +        <NuGetToolsPath>$(SolutionDir).nuget</NuGetToolsPath>
same as above

2022-07-20 08:56 UTC, alcxs commented on Activities/Directory.build.targets
> +		<PackageReference Update="System.Activities" Version="6.0.0-20220106-04" />
Update this to `UiPath.Workflow.Runtime` and match versions as in this document: https://docs.uipath.com/developer/docs/migrating-activities-to-net-5#:~:text=%3CPackageReference%20Update%3D%22UiPath.Workflow.Runtime%22%20Version%3D%226.0.0%2D20220401%2D03%22%20PrivateAssets%3D%22All%22/%3E

2022-07-20 08:56 UTC, alcxs commented on Activities/Scripting/UiPath.Scripting.Activities.Design/UiPath.Scripting.Activities.Design.csproj
> +		<PackageReference Include="System.Activities" />
same as above, modify to "UiPath.Workflow.Runtime"

2022-07-20 08:56 UTC, alcxs commented on Activities/Scripting/UiPath.Scripting.Activities.Design/UiPath.Scripting.Activities.Design.csproj
> +		<PackageReference Include="UiPath.Activities.Api" Version="21.10.4" />
remove version from here, leave it only in build.targets file

2022-07-20 08:56 UTC, alcxs commented on Activities/Scripting/UiPath.Scripting.Activities.Packaging/UiPath.Scripting.Activities.Packaging.csproj
> +		<PackageTitle>Nick.UiPath.Scripting.Activities</PackageTitle>
please cleanup this :)

2022-07-20 08:56 UTC, alcxs commented on Activities/Scripting/UiPath.Scripting.Activities.Packaging/UiPath.Scripting.Activities.Packaging.csproj
> +		<PackageTags>UiPathActivities</PackageTags>
check with PM what should be the actual tags here

2022-07-20 08:56 UTC, alcxs commented on Activities/Scripting/UiPath.Scripting.Activities.Packaging/UiPath.Scripting.Activities.Packaging.csproj
> +		<PackageReference Include="System.Activities" PrivateAssets="All"/>
same as above

2022-07-20 08:56 UTC, alcxs commented on Activities/Scripting/UiPath.Scripting.Activities/UiPath.Scripting.Activities.csproj
> +		<PackageReference Include="System.Activities" />
same as above - replace with `UiPath.Workflow.Runtime`

2022-07-20 09:02 UTC, nicolae-anghel commented on Activities/Scripting/UiPath.Scripting.Activities.Packaging/UiPath.Scripting.Activities.Packaging.csproj
> +		<PackageTitle>Nick.UiPath.Scripting.Activities</PackageTitle>
Fixed

2022-08-01 08:19 UTC, alcxs commented
Closing this as a new one was opened https://github.com/UiPath/Community.Activities/pull/278

2022-08-01 08:19 UTC, closed without merging